name: Test & Upload

on:
  push:

  workflow_dispatch:

jobs:
  test_and_publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: install
        run: |
          sudo apt install libhts-dev libhts3 libhtscodecs-dev libhtscodecs2 tabix
          pip install -U pip setuptools
          pip install -U pytest pytest-cov twine
          pip install .

      - name: Test
        run: |
          pytest
          
      - name: Build and Upload
        run: |
          python3 -m build
          python3 -m twine upload dist/*
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.TWINE_TEST_TOKEN }}
          TWINE_REPOSITORY: testpypi
  
