name: Python package

on:
  push:

jobs:
  cqa:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"
        cache: pip
        cache-dependency-path: '**/pyproject.toml'

    - name: Install dev dependencies
      run: |
        python -m pip install --upgrade pip
        pip install '.[dev]'

    - name: Lint with flake8
      run: |
        make cqa-flake8
        
    - name: Format check with isort
      run: |
        make cqa-isort

    - name: Format check with ruff
      run: |
        make cqa-ruff-format

    - name: Security check with bandit
      run: |
        make cqa-bandit

  test:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10", "3.11", "3.12"]

    steps:
    - name: Install packages
      run: |
        sudo apt install libhts-dev libhts3 libhtscodecs-dev libhtscodecs2 tabix

    - uses: actions/checkout@v3

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
        cache: pip
        cache-dependency-path: '**/setup.cfg'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install --use-deprecated=legacy-resolver '.[tests]'

    - name: Test with pytest
      run: |
        make test

  deploy:
    # See https://github.com/pypa/gh-action-pypi-publish/tree/release/v1?tab=readme-ov-file#usage
    needs:
    # - cqa
    - test
    runs-on: ubuntu-latest

    environment:
      name: pypi
      url: https://pypi.org/p/biocommons.seqrepo
    permissions:
      id-token: write  # mandatory for trusted publishing

    steps:
    - name: Environment
      run: |
        echo "::group::Environment info"
        echo github.event_name = ${{ github.event_name }}
        echo refs = ${{ github.ref }}
        echo tags = ${{ startsWith(github.ref, 'refs/tags') }}
        echo "::endgroup::"

    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"
        cache: pip
        cache-dependency-path: '**/setup.cfg'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build twine

    - name: Build package
      run: python -m build

    - name: Upload release to PyPI
      # Depends on trusted publishing configuration at pypi
      if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
      uses: pypa/gh-action-pypi-publish@release/v1
